project:
  type: book
  output-dir: "_site"

book:
  title: "Building tidy R packages for the OMOP common data model"
  author: "Edward Burn, Martí Català"
  date: today
  chapters:
  - index.qmd
  - part: getting_started/index.qmd
    chapters:
    - getting_started/scope.qmd
    - getting_started/ecosystem.qmd
    - getting_started/contributing.qmd
    - getting_started/setup.qmd
  - part: principles/index.qmd
    chapters:
    - principles/core_dependencies.qmd
    - principles/function_interfaces.qmd
    - principles/conventions.qmd
    - principles/error_and_validation.qmd
    - principles/function_outputs.qmd
    - principles/visualisations.qmd
    - principles/styling.qmd
    - principles/reexports.qmd
  - part: documentation/index.qmd
    chapters:
    - documentation/code.qmd
    - documentation/functions.qmd
    - documentation/readme.qmd
    - documentation/vignettes.qmd
    - documentation/website.qmd
  - part: testing/index.qmd
    chapters:
    - testing/introduction.qmd
    - testing/test_omop.qmd
    - testing/test_dbms.qmd
  - part: github/index.qmd
    chapters:
    - github/setup_github.qmd
    - github/automatic_checks.qmd
    - github/automatic_website.qmd
    - github/test_coverage.qmd
    - github/testing_multiple_dbms.qmd
  - part: maintainance/index.qmd
    chapters:
    - maintainance/releasing.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    titlepage: formal
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    keep-tex: true

editor: visual
